<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>TeraLink</AssemblyName>
    <Version>0.2.0</Version>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../TeraLink.Core/TeraLink.Core.csproj" /></ItemGroup>
</Project>
